project:
  type: book

book:
  title: "Handleidingen voor R(Studio)"
  # author: "Sander Vermeulen - van Gent"
  date: "9-30-2024"
  chapters:
    - toelichting.qmd
    - swing.qmd
    - databronnen.qmd
    - kaarten.qmd
 
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

